sudo: required
services:
  - docker

script:
  - pytest src/access/test/test.py
  - pytest src/chat/test/test.py
  - pytest src/match/test/test.py
  - pytest src/player/test/test.py
  - pytest src/ticket/test/test.py

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker-compose build
  - docker-compose push access chat gateway match player ticket