sudo: required
services:
  - docker

language: python
python:
  - "3.6"

script:
  - pip install pytest==4.6.5
  - pip install -r src/access/requirements.txt
  - pytest src/access/test/test.py
  - pip install -r src/chat/requirements.txt
  - pytest src/chat/test/test.py
  - pip install -r src/match/requirements.txt
  - pytest src/match/test/test.py
  - pip install -r src/player/requirements.txt
  - pytest src/player/test/test.py
  - pip install -r src/ticket/requirements.txt
  - pytest src/ticket/test/test.py

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker-compose build
  - docker-compose push access chat gateway match player ticket webapp