sudo: required
services:
  - docker

script:
  - docker-compose build

after_success:
  - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
