version: "3"
services:
  rabbitmq:
    container_name: games-rabbitmq
    image: rabbitmq:3.7-management
    ports:
      - "15673:15672"
    restart: always

  playerdb:
    container_name: games-playerdb
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: "player"
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "postgres"
    restart: always

  chat:
    container_name: games-chat
    build: ./src/chat
    restart: always
    depends_on:
      - rabbitmq
    links:
      - "rabbitmq:games-rabbitmq"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbitmq"
      RABBIT_PORT: "5672"
      RABBIT_MANAGEMENT_PORT: "15672"

  match:
    container_name: games-match
    build: ./src/match
    restart: always
    depends_on:
      - rabbitmq
    links:
      - "rabbitmq:games-rabbitmq"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbitmq"
      RABBIT_PORT: "5672"
      RABBIT_MANAGEMENT_PORT: "15672"

  player:
    container_name: games-player
    build: ./src/player
    restart: always
    depends_on:
      - rabbitmq
    links:
      - "rabbitmq:games-rabbitmq"
      - "playerdb:postgres"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbitmq"
      RABBIT_PORT: "5672"
      RABBIT_MANAGEMENT_PORT: "15672"
      DB_PASSWORD: "password"
      DB_USER: "postgres"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_NAME: "player"

  access:
    container_name: games-access
    build: ./src/access
    restart: always
    depends_on:
      - rabbitmq
    links:
      - "rabbitmq:games-rabbitmq"
      - "player"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbitmq"
      RABBIT_PORT: "5672"
      RABBIT_MANAGEMENT_PORT: "15672"

  ticket:
    container_name: games-ticket
    build: ./src/ticket
    restart: always
    depends_on:
      - rabbitmq
    links:
      - "rabbitmq:games-rabbitmq"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbitmq"
      RABBIT_PORT: "5672"
      RABBIT_MANAGEMENT_PORT: "15672"

  gateway:
    container_name: games-gateway
    build: ./src/gateway
    restart: "no"
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    links:
      - "rabbitmq:games-rabbitmq"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbitmq"
      RABBIT_PORT: "5672"
      RABBIT_MANAGEMENT_PORT: "15672"

  webapp:
    container_name: games-webapp
    build: ./src/webapp
    restart: always
    ports:
      - "8080:8080"
    links:
      - "gateway"
    environment:
      ENV: "prod"
